# -*- coding: utf-8 -*-
"""cv face.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xs-kFLs5QSd9nLdIDzNgQpwsoPdowN7w
"""

import cv2

image=cv2.imread("/content/people3.jpg")

image.shape

from google.colab.patches import cv2_imshow

cv2_imshow(image)

cv2.resize(image,(600,500))

im_gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
cv2_imshow(im_gray)

face_d=cv2.CascadeClassifier("/content/haarcascade_frontalface_default.xml")

detect=face_d.detectMultiScale(im_gray)

detect

detect.shape

detect_no=len(detect)

#no of faces
detect_no

for x,y,w,h in detect:
  cv2.rectangle(image,(x,y),(x+w,y+h),(0,300,0),3)

cv2_imshow(image)

eye_d=cv2.CascadeClassifier("/content/haarcascade_eye.xml")



image=cv2.imread("/content/po.jpg")
cv2.resize(image,(600,500))
print(image.shape)
im_gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
face_d=cv2.CascadeClassifier("/content/haarcascade_frontalface_default.xml")
eye_d=cv2.CascadeClassifier("/content/haarcascade_eye.xml")

detect=face_d.detectMultiScale(im_gray,scaleFactor=1.1)
for x,y,w,h in detect:
  cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),2)

eye=eye_d.detectMultiScale(im_gray,scaleFactor=1.3,minNeighbors=8,minSize=(5,5),maxSize=(35,35))
for x,y,w,h in eye:
  print(w,h)
  cv2.rectangle(image,(x,y),(x+w,y+h),(0,0,255),2)


cv2_imshow(image)



#face detection uuing hog(hist of gradiant) bttr than casscade
import dlib

face=cv2.imread("/content/people1.jpg")

face_hog=dlib.get_frontal_face_detector()

detectections=face_hog(face,1)
cv2_imshow(face)

detectections

for facee in detectections:
  x=facee.left()
  y=facee.top()
  w=facee.right()
  h=facee.bottom()
  cv2.rectangle(face,(x,y),(w,h),(0,255,255),2)
cv2_imshow(face)

## using cnn
img=cv2.imread("/content/people3.jpg")

cnn=dlib.cnn_face_detection_model_v1("/content/mmod_human_face_detector.dat")

de=cnn(img,1)
for face in de:
  l,t,r,b,c=face.rect.left(),face.rect.top(),face.rect.right(),face.rect.bottom(),face.confidence
  print(c)
  cv2.rectangle(img,(l,t),(r,b),(255,255,0),2)
cv2_imshow(img)



###face recognization

from PIL import Image
import numpy as np
import cv2
from google.colab.patches import cv2_imshow

import zipfile
path="/content/archive (1).zip"
zip_object=zipfile.ZipFile(file=path,mode="r")
zip_object.extractall("./")
zip_object.close()































